### ISSUE TITLE
How do I get the page title into the header?

### ISSUE THREAD

**Issue by skipdev** [stephyx/react-website#3]
https://github.com/stephyx/react-website/blob/b466378f817cc73484370ec597258357557e44cc/src/components/sidebar-top.js#L143

**Comment by skipdev** [comment]
https://github.com/stephyx/react-website/blob/b466378f817cc73484370ec597258357557e44cc/src/pages/about.js#L8

**Comment by alexpotter** [comment]
Top one just use

This is commented, should be `<p><b>{this.state.pageTitle}</b></p>`

The `{` is commenting the code

**Comment by alexpotter** [comment]
Second is fine, apart from the console, should be `this.state...`

**Comment by alexpotter** [comment]
My bad

https://github.com/stephyx/react-website/blob/b466378f817cc73484370ec597258357557e44cc/src/components/sidebar-top.js#L7

Inside 

```
state = {
    sidebarOpen: false, ,
    pageTitle: 'title',
}
```
